### ISSUE TITLE
db/_utils constant redirect

### ISSUE THREAD

**Issue by arpecop** [pouchdb/express-pouchdb#116]
Tried to access _utils and it redirects to urlback=noAccess?urlback=noAccess?urlback=noAccess?urlback=noAccess? (adding these values making browser to crash)

**Comment by nolanlawson** [comment]
fixed

**Comment by runia1** [comment]
@nolanlawson This doesn't appear to be fixed...

package.json
```
"express-pouchdb": "^1.0.7", 
"pouchdb-node": "^6.0.4",
```

server.js
`app.use('/api/v1', require('express-pouchdb')(PouchDB));`

In browser accessing via:

`<mydomain>/api/v1/_utils` doesn't work at all (no slash on end),

`<mydomain>/api/v1/_utils/` loads fauxton frame, but in Chrome console there are several 404's. Those include:

`<mydomain>/_session`
`<mydomain>/api/_session`
`<mydomain>/api/`
`<mydomain>/api/_session`

**Comment by sphaero** [comment]
I can confirm it isn't fixed:
```
GET /db/ 304 2.216 ms - -
GET /db/_utils/ 304 3.095 ms - -
GET /db/_utils/css/index-6688cd4426ead40b085270f8cb007530.css 304 8.199 ms - -
GET /db/_utils/js/require-34a7e370ea98389d118cc328682c0939.js 304 8.210 ms - -
GET /_session 404 1.114 ms - 21
GET /_session 404 0.613 ms - 21
GET /_session 404 0.654 ms - 21
GET / 304 0.992 ms - -
GET /db/_utils/img/pouchdb-site.png 304 3.013 ms - -
```

It still accessing _session from the root.

**Comment by jaunkst** [comment]
+1 broken

**Comment by lloydroc** [comment]
It’s unfortunate this can’t get fixed. It really makes CouchDB hard to use in production environments.

**Comment by HiveTechDev** [comment]
seems like this is still a thing in 2021. so seems like its always going to be.

**Comment by dheimoz** [comment]
hey @Koulwa would you mind creating a repo to revive this issue?
Thanks.
